import Head from "next/head";
import DefaultLayout from "../../layouts";
import { Grid, Typography, Button } from '@mui/material'
import Image from "next/image";


import { styled, } from '@mui/material/styles';

const MuiTypography = styled(Typography)({
    fontWeight: 900,
    fontStyle: "italic"
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
            <Grid container gap={1} display="flex" flexDirection="column" alignContent="center" paddingTop="5rem">
                <Grid item md={12} lg={12} display="flex" flexDirection="column" textAlign="center">
                  <MuiTypography variant="large" color="primary" sx={{ fontStyle: "normal" }}>Order</MuiTypography>
                  <MuiTypography variant="large">Delicious Meals From Your <br/>
                    Favourite Vendors
                  </MuiTypography>
                  <Typography variant="caption">Order Delicious Meals From Your Favourite  Vendors</Typography>
                </Grid>
                <Grid item md={12} textAlign="center">
                  <Button variant="contained" sx={{ width: "15rem", color: "white" }}>Place an order</Button>
                </Grid>
                <Grid item md={12}>
                  <Image src="/images/bakery.png" width="400" height="400" alt="bakery"></Image>
                </Grid>
            </Grid>
      </DefaultLayout>
    </>
  );
}
